apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: backend
      versio: ${BUILD_NUMBER}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: biswalashu/kasplo-backend:${BUILD_NUMBER}  # Replace with your actual Docker image and tag
        ports:
        - containerPort: 8000
