apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  replicas: 1  # Adjust the number of replicas as needed
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
        version: ${BUILD_NUMBER}
    spec:
      containers:
      - name: nginx
        image: biswalashu/kasplo-frontend:${BUILD_NUMBER}
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi"  # Adjust resource limits as needed
          requests:
            memory: "64Mi"   # Adjust resource requests as needed
